# JVM Configuration
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# AndroidX and Jetpack Compose
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true

# Kotlin Code Style
kotlin.code.style=official

# Parallel and Cache Optimization
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
